project_name = str(local('python3 scripts/dev/runtime.py project-name', quiet=True)).strip()
runtime_dir = str(local('python3 scripts/dev/runtime.py runtime-dir', quiet=True)).strip()
uid = str(local('id -u', quiet=True)).strip()
gid = str(local('id -g', quiet=True)).strip()
os.putenv('CHARGESHARE_PROJECT_NAME', project_name)
os.putenv('CHARGESHARE_RUNTIME_DIR', runtime_dir)
os.putenv('CHARGESHARE_BROKER_VOLUME', project_name + '_kafka-data')
os.putenv('CHARGESHARE_UID', uid)
os.putenv('CHARGESHARE_GID', gid)
if config.tilt_subcommand != 'down':
    local('python3 scripts/dev/runtime.py prepare', quiet=False)
local('python3 scripts/dev/runtime.py validate-config', quiet=False)
if config.tilt_subcommand != 'down' and os.getenv('CHARGESHARE_CI_PREBUILT_RECEIVER') == '1':
    docker_compose(local('python3 scripts/dev/cached_receiver.py compose', quiet=True), project_name=project_name)
else:
    docker_compose('dev/compose.yaml', project_name=project_name)
dc_resource('kafka', labels=['synthetic-transport'])
dc_resource('receiver', labels=['synthetic-transport'])
local_resource('rust-build', cmd='cargo build --workspace --locked', deps=['Cargo.toml', 'Cargo.lock', 'rust-toolchain.toml', 'crates'], labels=['build'])
local_resource('frontend-install', cmd='npm --cache .cache/npm --prefix apps/web ci', deps=['apps/web/package.json', 'apps/web/package-lock.json'], labels=['fixture-demo'])
local_resource('fixture-api', serve_cmd='exec target/debug/chargeshare-preview', resource_deps=['rust-build'], readiness_probe=probe(http_get=http_get_action(host='127.0.0.1', port=8787, path='/api/demo')), labels=['fixture-demo'])
local_resource('fixture-dashboard', serve_cmd='cd apps/web && exec node node_modules/vite/bin/vite.js', resource_deps=['frontend-install', 'fixture-api'], readiness_probe=probe(http_get=http_get_action(host='127.0.0.1', port=5173, path='/')), links=['http://127.0.0.1:5173'], labels=['fixture-demo'])
local_resource('receiver-ready', cmd='bash scripts/dev/harness.sh ready', resource_deps=['rust-build', 'receiver', 'kafka'], labels=['synthetic-transport'])
local_resource('telemetry-smoke', cmd='bash scripts/dev/harness.sh smoke', resource_deps=['receiver-ready'], trigger_mode=TRIGGER_MODE_MANUAL, auto_init=False, labels=['synthetic-transport'])
